import 'vuetify/styles'
import '@mdi/font/css/materialdesignicons.css'

import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'

export default defineNuxtPlugin((app) => {
  const vuetify = createVuetify({
    ssr: true,
    components,
    directives,
    theme: {
      defaultTheme: 'dark',
    themes: {
      light: {
        colors: {
          background: '#f4ece9',
          surface: '#fff8f5',
          'surface-dim': '#e0d9d5',
          'surface-bright': '#fff8f5',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#faf2ee',
          'surface-container': '#f4ece9',
          'surface-container-high': '#eee7e3',
          'surface-container-highest': '#e8e1dd',
          'on-surface': '#1e1b19',
          'inverse-surface': '#33302d',
          'inverse-on-surface': '#f7efeb',
          outline: '#7f766b',
          'outline-variant': '#d0c5b8',
          primary: '#6f5b3d',
          'on-primary': '#ffffff',
          'primary-container': '#fadeb9',
          'on-primary-container': '#271903',
          'inverse-primary': '#ddc39e',
          secondary: '#5e5e5e',
          'on-secondary': '#ffffff',
          'secondary-container': '#e3e2e2',
          'on-secondary-container': '#1b1c1c',
          tertiary: '#486363',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#cae8e8',
          'on-tertiary-container': '#022020',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#410002',
          'primary-fixed': '#fadeb9',
          'primary-fixed-dim': '#ddc39e',
          'on-primary-fixed': '#271903',
          'on-primary-fixed-variant': '#564428',
          'secondary-fixed': '#e3e2e2',
          'secondary-fixed-dim': '#c7c6c6',
          'on-secondary-fixed': '#1b1c1c',
          'on-secondary-fixed-variant': '#464747',
          'tertiary-fixed': '#cae8e8',
          'tertiary-fixed-dim': '#afcccc',
          'on-tertiary-fixed': '#022020',
          'on-tertiary-fixed-variant': '#304b4c',
          'surface-light': '#eee7e3',
        },
        dark: false,
        variables: {
          'overlay-background': '#201b13',
        },
      },
      dark: {
        colors: {
          background: '#221f1d',
          surface: '#151311',
          'surface-dim': '#151311',
          'surface-bright': '#3c3836',
          'surface-container-lowest': '#100e0c',
          'surface-container-low': '#1e1b19',
          'surface-container': '#221f1d',
          'surface-container-high': '#2d2927',
          'surface-container-highest': '#383432',
          'on-surface': '#e8e1dd',
          'inverse-surface': '#e8e1dd',
          'inverse-on-surface': '#33302d',
          outline: '#998f84',
          'outline-variant': '#4d463c',
          primary: '#ddc39e',
          'on-primary': '#3e2e14',
          'primary-container': '#564428',
          'on-primary-container': '#fadeb9',
          'inverse-primary': '#6f5b3d',
          secondary: '#c7c6c6',
          'on-secondary': '#303031',
          'secondary-container': '#464747',
          'on-secondary-container': '#e3e2e2',
          tertiary: '#afcccc',
          'on-tertiary': '#193535',
          'tertiary-container': '#304b4c',
          'on-tertiary-container': '#cae8e8',
          error: '#ffb4ab',
          'on-error': '#690005',
          'error-container': '#93000a',
          'on-error-container': '#ffb4ab',
          'primary-fixed': '#fadeb9',
          'primary-fixed-dim': '#ddc39e',
          'on-primary-fixed': '#271903',
          'on-primary-fixed-variant': '#564428',
          'secondary-fixed': '#e3e2e2',
          'secondary-fixed-dim': '#c7c6c6',
          'on-secondary-fixed': '#1b1c1c',
          'on-secondary-fixed-variant': '#464747',
          'tertiary-fixed': '#cae8e8',
          'tertiary-fixed-dim': '#afcccc',
          'on-tertiary-fixed': '#022020',
          'on-tertiary-fixed-variant': '#304b4c',
          'surface-light': '#3c3836',
        },
        dark: true,
        variables: {
          'overlay-background': '#201b13',
        },
      },
    },
    },
    defaults: {
      VCard: {
        rounded: 'lg',
        elevation: 0,
        color: 'surface',
      },
      VBtn: {
        rounded: 'lg',
        elevation: 0,
      },
      VChip: {
        rounded: 'lg',
        elevation: 0,
      },
      VTextField: {
        variant: 'outlined',
        density: 'comfortable',
      },
    },
  })

  app.vueApp.use(vuetify)
})
